name: Generate Bindings

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags: "*"

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  generate-bindings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.10.4"

      - run: julia --project=. -e 'import Pkg; Pkg.instantiate()'

      - run: julia --project=. generator.jl
